### ISSUE TITLE
Plugin does not work after the last update

### ISSUE THREAD

**Issue by DLaukhin** [ShockThunder/improved-random-note#1] opened 2023-09-18 07:11 UTC
Please check if the plugin can be fixed to work on the latest versions of Obsidian?

**Comment by ShockThunder** [comment] 2023-09-19 19:31
Hi! Thanks for informing me. I will check it and make update if possible

**Comment by DLaukhin** [comment] 2023-09-20 04:15
@ShockThunder не могу найти вас в телеге, если не сложно, пинганите dmitriylaukhin

**Comment by alexbofa** [comment] 2023-10-22 18:47
Hello, on version 1.4.16, the plugin does not load. Writes about the error `Failed to load the improved-random-note plugin`
![image](https://github.com/ShockThunder/improved-random-note/assets/58225118/fde227e6-d37f-4b13-8f8f-b54459405070)

UPD: After used [BRAT](https://github.com/TfTHacker/obsidian42-brat), it's work

**Comment by ShockThunder** [comment] 2023-10-23 14:49
> Hello, on version 1.4.16, the plugin does not load. Writes about the error `Failed to load the improved-random-note plugin` ![image](https://user-images.githubusercontent.com/58225118/277185953-fde227e6-d37f-4b13-8f8f-b54459405070.png)
> 
> UPD: After used [BRAT](https://github.com/TfTHacker/obsidian42-brat), it's work

Glad to know, that you find a solution.
You can also try to reinstall plugin.
I don't know what causing the error, because i have low data about it and can't reproduce.

**Comment by alexbofa** [comment] 2023-10-23 15:26
I used `git clone`, but after searching I found out that I only need to put 3 files in the `Obsidian\.obsidian\plugins` folder

**Comment by ShockThunder** [comment] 2023-11-08 04:16
> I used `git clone`, but after searching I found out that I only need to put 3 files in the `Obsidian\.obsidian\plugins` folder

Now plugin added to obsidian repo, so you can install it through community plugins tab. 

For now i close this issue due to lack of reproduction.

**Closed as not planned** 2023-11-08 04:16 UTC
